export const FETCH_LISTLOGO_SHOWTIME_SUCCESS = "ShowTimeReducer/FETCH_LISTLOGO_SHOWTIME_SUCCESS";
export const FETCH_LISTCINEMA_SHOWTIME_SUCCESS = "ShowTimeReducer/FETCH_LISTCINEMA_SHOWTIME_SUCCESS";
export const FETCH_MAHETHONGRAP_LOGOSHOWTIME = "ShowTimeReducer/FETCH_MAHETHONGRAP_LOGOSHOWTIME";
export const FETCH_MACUMRAP_SHOWTIME = "ShowTimeReducer/FETCH_MACUMRAP_SHOWTIME";
export const FETCH_LISTFILM_SHOWTIME = "ShowTimeReducer/FETCH_LISTFILM_SHOWTIME";
export const FETCH_MALICHCHIEU_FILM_SHOWTIME = "ShowTimeReducer/FETCH_MALICHCHIEU_FILM_SHOWTIME";

export const FETCH_INFO_DETAILFILM_SUCCESS = "DetailFilmReducer/FETCH_INFO_DETAILFILM_SUCCESS";
export const FETCH_INFO_DETAILFILM_FAILED = "DetailFilmReducer/FETCH_INFO_DETAILFILM_FAILED";
export const FETCH_INFO_DETAILFILM_REQUEST = "DetailFilmReducer/FETCH_INFO_DETAILFILM_REQUEST";