export const FETCH_LISTFILM_MANAGE = "Admin/FETCH_LISTFILM_MANAGE";
export const FETCH_ADDFILM_MANAGE = "Admin/FETCH_ADDFILM_MANAGE";
export const FETCH_DELETEFILM_MANAGE = "Admin/FETCH_DELETEFILM_MANAGE";


export const FETCH_DETAILFILM_MANAGE_SUCCESS = "Admin/FETCH_DETAILFILM_MANAGE_SUCCESS";
export const FETCH_DETAILFILM_MANAGE_FAILED = "Admin/FETCH_DETAILFILM_MANAGE_FAILED";
export const FETCH_DETAILFILM_MANAGE_REQUEST = "Admin/FETCH_DETAILFILM_MANAGE_REQUEST";

export const FETCH_EDITFILM_MANAGE_SUCCESS = "Admin/FETCH_EDITFILM_MANAGE_SUCCESS";

export const FETCH_HETHONGRAP_CREATE_SHOWTIME_MANAGE = "Admin/FETCH_HETHONGRAP_CREATE_SHOWTIME_MANAGE";
export const FETCH_LIST_LICHCHIEU_CREATE_SHOWTIME_MANAGE = "Admin/FETCH_LIST_LICHCHIEU_CREATE_SHOWTIME_MANAGE";


